'use strict';
(()=>{let user,users=[],before=null,resetTarget=null;const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(location.hostname.endsWith('github.io')){$('account-message').textContent='ここは操作デモです。アカウント管理は専用サーバーの準備後に利用できます。';document.querySelectorAll('input,button').forEach(e=>e.disabled=true);return;}
 async function request(url,method='GET',data){const r=await fetch(url,{method,headers:{'Content-Type':'application/json','X-CRM-Request':'1'},...(data?{body:JSON.stringify(data)}:{})});if(r.status===401){location.href='/login.html';throw Error('ログインしてください。');}const result=await r.json();if(!r.ok)throw Error(result.error);return result;}
 const run=fn=>async e=>{e?.preventDefault();try{await fn(e);$('account-message').textContent='操作が完了しました。';}catch(err){$('account-message').textContent=err.message;}};
 async function loadUsers(){users=await request('/api/users');$('user-list').innerHTML=users.map(u=>`<div class="account-user" data-user="${escape(u.id)}"><strong>${escape(u.name)}</strong> <small>${escape(u.login)} / ${u.active?'有効':'停止中'}</small><div class="account-user-controls"><select aria-label="${escape(u.name)}の権限"><option value="staff" ${u.role==='staff'?'selected':''}>担当者</option><option value="admin" ${u.role==='admin'?'selected':''}>管理者</option></select><button data-user-save>権限を保存</button><button data-user-toggle>${u.active?'停止':'再開'}</button><button data-user-password>パスワード再設定</button></div></div>`).join('');}
 async function loadAudit(reset=false){if(reset){before=null;$('audit-list').textContent='';}const rows=await request('/api/audit'+(before?'?before='+before:''));for(const a of rows){const el=document.createElement('article');el.className='account-audit';el.innerHTML=`<strong>${escape(a.action)} · ${escape(a.actor_name)}</strong><small>${escape(new Date(a.at).toLocaleString('ja-JP'))} / 操作者ID ${escape(a.actor_id)}</small>`;if(a.changes.length){const d=document.createElement('details'),s=document.createElement('summary');s.textContent='変更箇所を見る（'+a.changes.length+'）';d.append(s);for(const c of a.changes){const text=document.createElement('div');text.className='account-change';text.textContent=c.path+'\n変更前：'+JSON.stringify(c.before??'—')+'\n変更後：'+JSON.stringify(c.after??'—');d.append(text);}el.append(d);}$('audit-list').append(el);}if(rows.length)before=rows.at(-1).id;$('audit-more').hidden=rows.length<50;}
 async function loadBackup(){const b=await request('/api/backups');$('backup-status').textContent=b.status?.ok?'最終成功：'+new Date(b.status.at).toLocaleString('ja-JP')+' / '+Math.ceil(b.status.bytes/1024)+'KB':b.status?'前回失敗：サーバーの空き容量と権限を確認してください。':'まだ作成されていません。';}
 $('logout').onclick=run(async()=>{await request('/api/logout','POST',{});location.href='/login.html';});
 $('password-form').onsubmit=run(async e=>{const form=e.currentTarget;await request('/api/password','POST',Object.fromEntries(new FormData(form)));form.reset();location.href='/login.html';});
 $('user-form').onsubmit=run(async e=>{const form=e.currentTarget;await request('/api/users','POST',Object.fromEntries(new FormData(form)));form.reset();await loadUsers();});
 $('user-list').onclick=run(async e=>{const row=e.target.closest('[data-user]');if(!row)return;const u=users.find(x=>x.id===row.dataset.user);if(e.target.matches('[data-user-password]')){resetTarget=u;$('reset-password-form').reset();$('reset-password-error').textContent='';$('reset-password-dialog').showModal();return;}if(!e.target.matches('[data-user-save],[data-user-toggle]'))return;if(!confirm('アカウント設定を変更しますか？ 対象者の全端末がログアウトします。'))return;await request('/api/users/'+u.id,'PATCH',{role:row.querySelector('select').value,active:e.target.matches('[data-user-toggle]')?!u.active:u.active});await loadUsers();});
 $('reset-password-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;try{await request('/api/users/'+resetTarget.id,'PATCH',{role:resetTarget.role,active:resetTarget.active,password:form.elements.password.value});form.reset();$('reset-password-dialog').close();await loadUsers();}catch(err){$('reset-password-error').textContent=err.message;}};
 $('reset-password-close').onclick=()=>$('reset-password-dialog').close();$('audit-refresh').onclick=run(()=>loadAudit(true));$('audit-more').onclick=run(()=>loadAudit());$('backup-now').onclick=run(async()=>{await request('/api/backups','POST',{});await loadBackup();});
 (async()=>{try{const info=await request('/api/me');user=info.user;$('who').textContent=user.name+' / '+(user.role==='admin'?'管理者':'担当者');$('change-required').hidden=!user.mustChange;$('admin-panel').hidden=user.role!=='admin'||user.mustChange;if(user.role==='admin'&&!user.mustChange)await Promise.all([loadUsers(),loadAudit(true),loadBackup()]);}catch(e){$('account-message').textContent='専用サーバーで開いてください。'+e.message;}})();
})();
