'use strict';
(()=>{const G=CRMAds,S=CRMWorkbench,A=AdCore,clone=x=>JSON.parse(JSON.stringify(x)),onPage=['advertising','acquisition'].includes(document.body.dataset.page);let tab='overview',editRecord='',editLead='',sample=false,importDraft=null,journeyLimit=50,recordLimit=50;
const work=()=>S.state,ads=()=>G.data(work()),option=(v,l=v)=>`<option value="${esc(v)}">${esc(l)}</option>`,button=(id,l)=>`<button type="button" class="fc-secondary" id="${id}">${l}</button>`;
const money=n=>n===null?'—':yen(n),number=n=>n===null?'—':new Intl.NumberFormat('ja-JP',{maximumFractionDigits:2}).format(n),percent=n=>n===null?'—':number(n)+'%';
const sourceFields=()=>`<label>LP<select name="lp"></select></label><label>広告媒体<select name="medium"></select></label><label>流入経路<select name="channel">${G.channels.map(c=>option(c)).join('')}</select></label>`;
const field=(name,label,type='number',required=true)=>`<label>${label}<input name="${name}" type="${type}" ${required?'required':''} ${type==='number'?'min="0" max="10000000000" step="1" inputmode="numeric"':type==='date'?'min="2000-01-01" max="2099-12-31"':'maxlength="160"'}></label>`;
$('#ads-section').innerHTML=`<div class="mg-heading"><h2>広告から利益まで</h2><button id="ad-sample" class="fc-secondary">架空サンプルを見る</button></div><p id="ad-sample-note" class="wb-alert" hidden>架空サンプルを閲覧中です。保存データとは混ざりません。</p><p id="ad-error" class="fc-error" role="alert"></p>
<div class="ad-tabs" role="group" aria-label="広告メニュー">${[['overview','分析'],['records','広告入力'],['leads','送客・顧客'],['catalog','LP・媒体管理'],['migration','データ移行']].map(([k,l])=>`<button data-ad-tab="${k}" aria-pressed="${k==='overview'}">${l}</button>`).join('')}</div>
<form id="ad-filter" class="ad-filter"><div class="ad-quick">${[['yesterday','昨日'],['today','今日'],['month','今月'],['previous','先月'],['all','全期間']].map(([k,l])=>`<button type="button" data-ad-period="${k}">${l}</button>`).join('')}</div><div class="ad-fields">${field('start','開始日','date')}${field('end','終了日','date')}${sourceFields()}</div></form>
<div data-ad-panel="overview"><div id="ad-kpis" class="ad-kpis"></div><p class="fc-note">売上・成果は案件から自動集計。利益は広告費控除後の見込です。</p><div id="ad-funnel" class="ad-funnel"></div><details class="mg-definitions"><summary>前日比・前月比</summary><div id="ad-comparisons"></div></details><details class="mg-definitions"><summary>単価・率（CPA / CTR / CVR / ROASなど）</summary><div id="ad-ratios" class="ad-ratios"></div></details>
<div class="ad-fields"><label>表示区分<select id="ad-group">${[['lp','LP別ランキング'],['medium','媒体別ランキング'],['channel','流入経路別'],['day','日別推移'],['month','月別推移']].map(([k,l])=>option(k,l)).join('')}</select></label><label>並び順<select id="ad-sort">${[['profit','利益'],['spend','広告費'],['visits','送客数'],['conversions','成果数']].map(([k,l])=>option(k,l)).join('')}</select></label>${button('ad-export','集計CSVを保存')}</div><div id="ad-chart" class="ad-chart"></div><p class="ad-scroll-hint">表は横にスクロールできます。</p><div id="ad-ranking" class="numeric-scroll" tabindex="0" role="region" aria-label="LP・媒体別の集計表"></div><div id="ad-quality" class="fc-note"></div>
<details class="mg-definitions"><summary>集計・二重計上を防ぐ仕組み</summary><p>広告費・表示・クリック・広告のその他費用だけを広告入力で記録。送客は名簿から自動集計し、顧客・案件と紐付けます。成果＝買取済案件数、売上＝請求書額面−買取額（手数料見込）、利益＝手数料見込−案件の直接費用−広告費−広告のその他費用。回収元本・旧売上台帳・旧Ad Noteの手入力成果／売上／利益は合算しません。案件の費用を広告費欄へ再入力しないでください。</p><p>送客は送客日、登録顧客は流入日、申込は申込日、成果・売上は買取日で集計します。期間内の活動比較であり、同じ送客集団だけを追う成約率ではありません。1人に複数案件があれば成果も複数件です。案件に再送客を指定しない場合は顧客の初回流入へ帰属します。</p><p>旧Ad Noteから移した送客数は同じ日付・LP・媒体・経路の「総数」です。名簿の人数を足さず、総数と名簿人数の大きい方を採用します。差分は未紐付け人数として表示。人物の一致は自動判定せず、名簿の重複は登録時に確認してください。LP・媒体不明の旧顧客は未設定のままです。</p><p>前日比は今日と昨日、前月比は今月1日〜今日と先月同日まで（短い月は月末）。絞り込みは共通ですが、比較期間は上の指定期間とは別です。0分母は「—」。利益の赤字は赤と文字で表示。API連携・LINE取得・端末間同期はありません。</p></details></div>
<div data-ad-panel="records" hidden><div class="ad-toolbar">${button('ad-add-record','＋ 広告入力')}${button('ad-record-csv','入力明細CSV')}</div><p class="fc-note">成果・売上・利益の入力は不要です。案件の保存・訂正が分析に反映されます。</p><div id="ad-records"></div>${button('ad-more-records','さらに50件表示')}</div>
<div data-ad-panel="leads" hidden><div class="ad-toolbar">${button('ad-add-lead','＋ 送客を登録')}${button('ad-add-customer','＋ 顧客を登録')}</div><p class="fc-note">送客だけ先に登録でき、後から既存顧客へ紐付け・新規顧客化できます。同じ方の重複登録にご注意ください。</p><div id="ad-journeys"></div>${button('ad-more-leads','さらに50件表示')}</div>
<div data-ad-panel="catalog" hidden><form id="ad-catalog" class="ad-fields"><label>種別<select name="field">${option('lp','LP')}${option('medium','広告媒体')}</select></label><label>編集対象<select name="oldName"><option value="">新しく追加</option></select></label>${field('newName','登録名','text')}<button class="primary">登録・変更を保存</button></form><p class="fc-note">改名は広告・送客・顧客へ一括反映します。過去の集計も新しい名前になります。旧Ad Note原本は変更しません。</p><div id="ad-catalog-list"></div></div>
<div data-ad-panel="migration" hidden><h3>以前のAd Noteから取り込む</h3><p>このブラウザのAd Noteデータ、またはJSONバックアップを取り込めます。CRMの顧客・案件は消しません。同じ記録の再取込はスキップします。</p><div class="ad-toolbar">${button('ad-import-local','このブラウザのAd Noteを確認')}<label class="wb-file-label">Ad NoteのJSONを選択<input id="ad-import-file" type="file" accept=".json,application/json"></label></div><p id="ad-import-preview" role="status"></p><button id="ad-import-apply" class="primary" hidden>確認した広告データを取り込む</button><p class="fc-note">旧売上・利益・成果は参照履歴として残り、案件と二重合算しません。別の端末のデータは元の端末でJSONを書き出してください。</p><details class="mg-definitions"><summary>旧Ad Noteの手入力集計・原本</summary>${button('ad-legacy-export','旧Ad Note原本JSONを保存')}<div id="ad-legacy"></div></details><details class="mg-definitions"><summary>旧CRMの広告費累計（参照のみ）</summary><p>日付・LPが不明な旧累計は新しい広告費へ足していません。Ad Noteと重複しないことを確認した未登録分だけ、広告入力へ記録してください。</p><div id="ad-old-budgets"></div></details><p><a href="backup.html">顧客・案件・広告をまとめてバックアップ／復元 →</a></p></div>`;
const dialog=(id,title,body)=>{const d=document.createElement('dialog');d.id=id;d.className='ad-dialog';d.innerHTML=`<div class="drawer-header"><h2>${title}</h2><button type="button" class="icon-button" data-ad-close="${id}" aria-label="閉じる">×</button></div>${body}`;document.body.append(d);};
dialog('ad-record-dialog','広告実績を入力',`<form id="ad-record-form"><div class="ad-fields">${field('date','日付','date')}${sourceFields()}${field('spend','広告費（円）')}${field('impressions','表示回数')}${field('clicks','クリック数')}${field('other','広告のその他費用（円）')}${field('visits','送客総数（空欄＝名簿から自動）','number',false)}</div><p class="fc-note">送客総数は名簿人数への加算ではありません。過去の人数だけ分かる場合に使います。通常は空欄のまま登録してください。</p><label>メモ<textarea name="note" maxlength="500"></textarea></label><p id="ad-record-error" class="fc-error" role="alert"></p><button class="primary">広告実績を保存</button></form>`);
dialog('ad-lead-dialog','送客・顧客を登録',`<form id="ad-lead-form"><div class="ad-fields">${field('date','送客日','date')}${sourceFields()}${field('name','名前・管理用の呼び名','text',false)}<label>顧客への紐付け<select name="customerId"></select></label></div><p class="fc-note">登録済みの方は既存顧客を選んでください。新規顧客化すると、この流入情報を引き継ぎます。</p><label class="ops-check"><input name="primarySource" type="checkbox">この送客を顧客の初回流入として使う（既存の初回流入を置換）</label><label>メモ<textarea name="note" maxlength="500"></textarea></label><p id="ad-lead-error" class="fc-error" role="alert"></p><button class="primary">送客・紐付けを保存</button></form>`);
function choices(form,filters=false){const cat=G.catalog(customers,work());for(const k of ['lp','medium']){const e=form.elements[k];if(!e)continue;const v=e.value;e.innerHTML=option('',filters?'すべて':'未設定')+cat[k].map(x=>option(x)).join('');e.value=cat[k].includes(v)?v:'';}if(filters){const e=form.elements.channel,v=e.value;e.innerHTML=option('','すべて')+G.channels.map(x=>option(x)).join('');e.value=v;}}
const filter=$('#ad-filter');choices(filter,true);filter.elements.channel.value='';filter.elements.start.value=today().slice(0,7)+'-01';filter.elements.end.value=today();
function filters(){const v=Object.fromEntries(new FormData(filter));if(!A.validDate(v.start)||!A.validDate(v.end)||v.start>v.end)throw Error('開始日と終了日を確認してください。');return v;}
function sampleData(){const day=today(),src={lp:'サンプルLP',medium:'サンプル媒体',channel:'広告'},c={id:'SAMPLE',name:'サンプル顧客',created:stamp(),acquisition:{...src,date:day},factoringCases:[{id:'SAMPLE-CASE',status:'purchased',applicationDate:day,purchaseDate:day,invoiceAmount:100000,purchaseAmount:80000,cost:2000,receipts:[]}]};return {people:[c],work:{ads:{...G.defaults(),records:[{id:'SAMPLE-AD',date:day,...src,spend:5000,impressions:1000,clicks:50,other:0,visits:null,note:''}]}}};}
const current=()=>sample?sampleData():{people:customers,work:work()};
const kpis=[['spend','広告費',money],['clicks','クリック数',number],['visits','送客数',number],['conversions','成果（買取済）',number],['revenue','売上（手数料見込）',money],['profit','広告費控除後の見込利益',money]];
const cards=t=>kpis.map(([k,l,f])=>`<div class="ad-kpi"><span>${l}</span><strong data-ad-kpi="${k}" class="${t[k]<0?'negative':''}">${f(t[k])}</strong>${k==='profit'&&t[k]<0?'<small class="negative">赤字</small>':''}</div>`).join('');
const table=rows=>`<table class="fc-table"><thead><tr><th>区分</th><th>広告費</th><th>送客</th><th>顧客</th><th>申込</th><th>成果</th><th>手数料見込</th><th>広告費控除後利益</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.profit<0?'ad-loss':''}"><th>${esc(r.label)}</th><td>${money(r.spend)}</td><td>${number(r.visits)}</td><td>${r.customers}</td><td>${r.applications}</td><td>${r.conversions}</td><td>${money(r.revenue)}</td><td>${money(r.profit)} ${r.profit<0?'赤字':''}</td></tr>`).join('')}</tbody></table>`;
function comparisons(people,w,v){$('#ad-comparisons').innerHTML=['day','month'].map(mode=>{const r=A.comparisonRanges(today(),mode),get=range=>G.analyze(people,w,{...v,start:range[0],end:range[1]}).total,n=get(r.current),p=get(r.previous);return `<h3>${mode==='day'?'今日／昨日':'今月／先月同日まで'}</h3><p>${r.current.join('〜')} ／ ${r.previous.join('〜')}</p><div class="ad-ratios">${kpis.map(([k,l,f])=>{const c=A.change(n[k],p[k]);return `<div><span>${l}</span><b>${f(n[k])}</b><small>前期 ${f(p[k])} ／ ${c.percent===null?'—（比較元0）':(c.percent>0?'+':'')+percent(c.percent)}</small></div>`}).join('')}</div>`;}).join('');}
function rowsFiltered(){const v=filters();return ads().records.filter(r=>r.date>=v.start&&r.date<=v.end&&(!v.lp||r.lp===v.lp)&&(!v.medium||r.medium===v.medium)&&(!v.channel||r.channel===v.channel)).sort((a,b)=>b.date.localeCompare(a.date));}
function renderRecords(){const rs=rowsFiltered();$('#ad-records').innerHTML=rs.slice(0,recordLimit).map(r=>`<article class="ad-list-row"><div><strong>${esc(r.lp||'LP未設定')} / ${esc(r.medium||'媒体未設定')}</strong><small>${r.date} · ${esc(r.channel)}</small><p>広告費 ${money(r.spend)} · ${number(r.clicks)}クリック · 送客 ${r.visits===null?'名簿から自動':r.visits+'人（総数）'}</p>${r.note?'<p>'+esc(r.note)+'</p>':''}</div><div class="ad-actions"><button data-ad-edit="${esc(r.id)}">編集</button><button data-ad-copy="${esc(r.id)}">複製</button><button data-ad-delete="${esc(r.id)}">削除</button></div></article>`).join('')||'<p class="empty">この期間の広告入力はありません。</p>';$('#ad-more-records').hidden=rs.length<=recordLimit;}
function renderJourneys(){const v=filters(),ds=ads(),events=G.events(customers,work()).filter(l=>(!l.date||l.date>=v.start&&l.date<=v.end)&&(!v.lp||l.lp===v.lp)&&(!v.medium||l.medium===v.medium)&&(!v.channel||l.channel===v.channel)).sort((a,b)=>b.date.localeCompare(a.date));const byId=new Map(customers.map(c=>[c.id,c]));
 $('#ad-journeys').innerHTML=events.slice(0,journeyLimit).map(l=>{const c=byId.get(l.customerId),cases=(c?.factoringCases||[]).filter(a=>!a.void&&(a.adLeadId?a.adLeadId===l.id:l.implicit||c.acquisition?.leadId===l.id));return `<article class="ad-list-row"><div><strong>${esc(l.name||c?.name||'送客 '+l.id)}</strong><small>${esc(l.date||'送客日未設定')} · ${esc(l.channel)} / ${esc(l.medium||'媒体未設定')} / ${esc(l.lp||'LP未設定')}</small><p>送客 → ${c?'顧客登録済み':'顧客未紐付け'} → ${cases.length}案件 / ${cases.filter(a=>a.status==='purchased').length}成果</p><div class="ad-case-links">${cases.map(a=>`<button data-ad-case="${esc(a.id)}">${esc(a.reference||a.id)} · ${CRMFactoring.labels[a.status]}${a.status==='purchased'?' / 手数料 '+money(a.invoiceAmount-a.purchaseAmount)+' / 案件見込利益（広告費控除前） '+money(a.invoiceAmount-a.purchaseAmount-a.cost):''}</button>`).join('')}</div></div><div class="ad-actions">${!l.implicit?`<button data-ad-lead="${esc(l.id)}">${c?'送客を編集':'顧客化・紐付け'}</button>`:''}${c?`<button data-ad-customer="${esc(c.id)}">顧客詳細</button><a href="cases.html?customer=${encodeURIComponent(c.id)}">案件を登録</a>`:''}${!c&&!l.implicit?`<button data-ad-lead-delete="${esc(l.id)}">削除</button>`:''}</div></article>`;}).join('')||'<p class="empty">該当する送客はありません。</p>';$('#ad-more-leads').hidden=events.length<=journeyLimit;}
function renderCatalog(){const f=$('#ad-catalog'),cat=G.catalog(customers,work()),old=f.elements.oldName.value;f.elements.oldName.innerHTML=option('','新しく追加')+cat[f.elements.field.value].map(v=>option(v)).join('');f.elements.oldName.value=cat[f.elements.field.value].includes(old)?old:'';$('#ad-catalog-list').innerHTML=['lp','medium'].map(k=>`<h3>${k==='lp'?'LP':'広告媒体'} ${cat[k].length}件</h3><p>${cat[k].map(esc).join(' ／ ')||'未登録'}</p>`).join('');}
function draw(){try{if(!onPage)return;const v=filters(),{people,work:w}=current(),result=G.analyze(people,w,v),t=result.total;$('#ad-error').textContent=S.blocked||'';$('#ad-kpis').innerHTML=cards(t);$('#ad-funnel').innerHTML=[['送客',t.visits],['顧客',t.customers],['案件',t.applications],['成果',t.conversions]].map(([l,n])=>`<div><small>${l}</small><b>${n}</b></div>`).join('');comparisons(people,w,v);
 $('#ad-ratios').innerHTML=[['costPerVisit','1送客あたり広告費',money],['cpa','1成果あたり広告費',money],['profitPerVisit','1送客あたり利益',money],['ctr','CTR',percent],['cvr','CVR',percent],['roas','ROAS',percent],['cpc','CPC',money],['cpm','CPM',money],['visitRate','送客率',percent],['closeRate','送客後成果率',percent],['margin','利益率',percent]].map(([k,l,f])=>`<div><span>${l}</span><b class="${t[k]<0?'negative':''}">${f(t[k])}</b></div>`).join('');
 const mode=$('#ad-group').value,sort=$('#ad-sort').value,groups=G.group(result.rows,mode).sort((a,b)=>['day','month'].includes(mode)?a.label.localeCompare(b.label):b[sort]-a[sort]||a.label.localeCompare(b.label));$('#ad-ranking').innerHTML=groups.length?table(groups):'<p class="empty">この条件の実績はありません。</p>';const max=Math.max(1,...groups.map(r=>Math.abs(r[sort])));$('#ad-chart').innerHTML=groups.slice(0,30).map(r=>`<div class="ad-bar ${r.profit<0?'ad-loss':''}"><span>${esc(r.label)}</span><i style="width:${Math.max(0,Math.abs(r[sort])/max*100)}%"></i><b>${['profit','spend'].includes(sort)?money(r[sort]):number(r[sort])}${r.profit<0?' · 赤字':''}</b></div>`).join('');
 $('#ad-quality').textContent=`送客名簿 ${t.identified}件 / 総数だけで人物未紐付け ${result.manualRemainder}人${result.missingDates?' ／ 送客日未設定 '+result.missingDates+'件（期間集計外）':''}${result.overReported?' ／ 名簿人数が手入力総数を超えた '+result.overReported+'組：名簿人数を採用':''}。`;renderRecords();renderJourneys();renderCatalog();const legacy=ads().records.filter(r=>r.legacy).map(r=>r.legacy);$('#ad-legacy').innerHTML=legacy.length?`<p>${legacy.length}件の取込原本を保持。下記は統合集計には加算しません。</p><div class="numeric-scroll"><table class="fc-table"><tr><th>日付・LP・媒体</th><th>成果</th><th>手入力売上</th><th>旧利益</th></tr>${legacy.map(r=>`<tr><td>${r.date} / ${esc(r.lp)} / ${esc(r.medium)}</td><td>${r.conversions}</td><td>${money(r.revenue)}</td><td>${money(A.profit(r))}</td></tr>`).join('')}</table></div>`:'<p>取込原本はありません。</p>';$('#ad-old-budgets').innerHTML=Object.entries(work().budgets).map(([k,n])=>`<p>${esc(k)}：${money(n)}</p>`).join('')||'<p>旧累計なし</p>';$('#ad-sample-note').hidden=!sample;$('#ad-sample').textContent=sample?'自分のデータに戻る':'架空サンプルを見る';document.querySelectorAll('[data-ad-tab]').forEach(b=>b.disabled=sample&&b.dataset.adTab!=='overview');}catch(e){$('#ad-error').textContent=e.message;}}
function selectTab(k){tab=k;document.querySelectorAll('[data-ad-panel]').forEach(p=>p.hidden=p.dataset.adPanel!==k);document.querySelectorAll('[data-ad-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.adTab===k)));filter.hidden=['catalog','migration'].includes(k);draw();}
function assertWrite(){if(sample)throw Error('サンプル表示中は保存できません。');if(loadError||S.blocked)throw Error('保存データを読み込めません。バックアップから復元してください。');if(S.locked)throw Error('書込ロック中です。保存・バックアップから解除してください。');}
async function saveBoth(cs,w,message){assertWrite();G.validateLinks(cs,w);w.history=[...w.history,{at:stamp(),text:message}];await S.restore(cs,w);customers=cs;choices(filter,true);render();draw();notify(message);}
async function saveWork(w,message){await saveBoth(customers,w,message);}
const draft=()=>{const w=clone(work());w.ads=clone(ads());return w;};
function openRecord(id='',copy=false){assertWrite();const f=$('#ad-record-form'),r=ads().records.find(r=>r.id===id);editRecord=copy?'':id;f.reset();choices(f);f.elements.date.value=copy||!r?today():r.date;for(const k of ['lp','medium','channel','spend','impressions','clicks','other','visits','note'])f.elements[k].value=r?r[k]??'':k==='channel'?'広告':['spend','impressions','clicks','other'].includes(k)?0:'';$('#ad-record-error').textContent='';showDialog('ad-record-dialog');}
const snapshots=new Map();function formSnapshot(d){return JSON.stringify([...new FormData(d.querySelector('form'))]);}function showDialog(id){const d=$('#'+id);d.showModal();snapshots.set(id,formSnapshot(d));}function closeDialog(id){const d=$('#'+id);if(formSnapshot(d)!==snapshots.get(id)&&!confirm('未保存の入力を破棄して閉じますか？'))return;d.close();}
for(const id of ['ad-record-dialog','ad-lead-dialog'])$('#'+id).addEventListener('cancel',e=>{e.preventDefault();closeDialog(id);});
$('#ad-record-form').onsubmit=async e=>{e.preventDefault();$('#ad-record-error').textContent='';try{assertWrite();const f=e.currentTarget,w=draft(),old=w.ads.records.find(r=>r.id===editRecord),r={...(old||{}),id:editRecord||'AD-'+crypto.randomUUID()};for(const k of ['date','lp','medium','channel','note'])r[k]=f.elements[k].value.trim();for(const k of ['spend','impressions','clicks','other'])r[k]=Number(f.elements[k].value);r.visits=f.elements.visits.value===''?null:Number(f.elements.visits.value);w.ads.records=old?w.ads.records.map(x=>x.id===editRecord?r:x):[...w.ads.records,r];await saveWork(w,'広告実績を保存しました。');$('#ad-record-dialog').close();}catch(err){$('#ad-record-error').textContent=err.message;}};
function openLead(id='',newCustomer=false){assertWrite();const f=$('#ad-lead-form'),l=ads().leads.find(l=>l.id===id);editLead=id;f.reset();choices(f);for(const k of ['date','lp','medium','channel','name','note'])f.elements[k].value=l?l[k]:k==='date'?today():k==='channel'?'広告':'';f.elements.customerId.innerHTML=option('','送客のみ（顧客未登録）')+option('__new','新しい顧客として登録')+customers.map(c=>option(c.id,c.name+' · '+c.id)).join('');f.elements.customerId.value=l?.customerId||((id||newCustomer)?'__new':'');f.elements.customerId.disabled=!!l?.customerId;f.elements.primarySource.checked=!!l&&customers.find(c=>c.id===l.customerId)?.acquisition?.leadId===l.id||newCustomer;f.elements.primarySource.disabled=!!l&&customers.find(c=>c.id===l.customerId)?.acquisition?.leadId===l.id;$('#ad-lead-error').textContent='';showDialog('ad-lead-dialog');}
$('#ad-lead-form').onsubmit=async e=>{e.preventDefault();$('#ad-lead-error').textContent='';try{assertWrite();const f=e.currentTarget,w=draft(),cs=clone(customers),previous=w.ads.leads.find(l=>l.id===editLead);let cid=f.elements.customerId.value;const l={id:editLead||'LEAD-'+crypto.randomUUID(),customerId:cid};for(const k of ['date','lp','medium','channel','name','note'])l[k]=f.elements[k].value.trim();if(cid==='__new'){if(!l.name)throw Error('新規顧客の名前を入力してください。');if(cs.some(c=>c.name===l.name)&&!confirm('同じ名前の顧客がいます。別のお客様として新規登録しますか？'))return;cid='CUSTOMER-'+crypto.randomUUID();l.customerId=cid;cs.unshift({id:cid,name:l.name,phone:'',lineName:'',status:'new',owner:'',due:'',next:'',message:l.note,created:stamp(),acquisition:{...G.source(l),date:l.date,leadId:l.id},transactions:[],factoringCases:[],legalNotices:[],history:[{at:stamp(),text:'送客から顧客を登録：'+l.lp+' / '+l.medium}]});}
 if(previous?.customerId&&previous.customerId!==cid)throw Error('紐付け済み顧客の変更はできません。');if(cid){const c=cs.find(c=>c.id===cid);if(!c)throw Error('顧客を確認してください。');if(f.elements.primarySource.checked||c.acquisition?.leadId===l.id){c.acquisition={...(c.acquisition||{}),...G.source(l),date:l.date,leadId:l.id};c.history.push({at:stamp(),text:'送客の紐付け・流入情報を保存：'+l.id});}if(!l.name)l.name=c.name;}
 w.ads.leads=previous?w.ads.leads.map(x=>x.id===l.id?l:x):[...w.ads.leads,l];await saveBoth(cs,w,'送客・顧客の紐付けを保存しました。');$('#ad-lead-dialog').close();}catch(err){$('#ad-lead-error').textContent=err.message;}};
$('#ad-catalog').elements.field.onchange=renderCatalog;$('#ad-catalog').elements.oldName.onchange=e=>$('#ad-catalog').elements.newName.value=e.target.value;
$('#ad-catalog').onsubmit=async e=>{e.preventDefault();try{assertWrite();const f=e.currentTarget,old=f.elements.oldName.value;if(old&&!confirm('「'+old+'」を「'+f.elements.newName.value+'」へ変更しますか？ 過去の広告・送客・顧客にも反映します。'))return;const result=G.rename(customers,work(),f.elements.field.value,old,f.elements.newName.value);await saveBoth(result.customers,result.work,'LP・媒体登録を保存しました。');f.elements.newName.value='';}catch(err){$('#ad-error').textContent=err.message;}};
function previewImport(raw){assertWrite();const result=G.importNote(work(),raw);importDraft={raw,snapshot:JSON.stringify(work())};$('#ad-import-preview').textContent=`追加 ${result.added}件 ／ 取込済み ${result.skipped}件。顧客・案件は維持、旧売上は参照として保存します。`;$('#ad-import-apply').hidden=result.added===0;}
$('#ad-import-local').onclick=()=>{try{const raw=localStorage.getItem('osanai-ad-manager-v1');if(!raw)throw Error('このブラウザにAd Noteのデータがありません。元の端末からJSONを保存し、選択してください。');previewImport(raw);}catch(e){$('#ad-error').textContent=e.message;}};
$('#ad-import-file').onchange=async e=>{importDraft=null;$('#ad-import-apply').hidden=true;try{const file=e.target.files[0];if(!file)return;if(file.size>12000000)throw Error('12MB以内のJSONを選んでください。');previewImport(await file.text());}catch(err){$('#ad-error').textContent=err.message;}e.target.value='';};
$('#ad-import-apply').onclick=async()=>{try{assertWrite();if(!importDraft)return;if(JSON.stringify(work())!==importDraft.snapshot)throw Error('確認後にデータが変わりました。もう一度取込内容を確認してください。');if(!confirm('確認した広告データを追加しますか？ 元のAd Noteは変更しません。'))return;const r=G.importNote(work(),importDraft.raw);await saveWork(r.work,'Ad Note '+r.added+'件を取り込みました。');importDraft=null;$('#ad-import-apply').hidden=true;$('#ad-import-preview').textContent='取込完了。広告入力・分析をご確認ください。';}catch(e){$('#ad-error').textContent=e.message;}};
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type:type||'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
const csv=rows=>'\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');
$('#ad-export').onclick=()=>{try{const {people,work:w}=current(),rows=G.group(G.analyze(people,w,filters()).rows,$('#ad-group').value);download('広告集計-'+today()+'.csv',csv([['区分','広告費','クリック','送客','顧客','申込','成果','手数料見込','広告費控除後見込利益'],...rows.map(r=>[r.label,r.spend,r.clicks,r.visits,r.customers,r.applications,r.conversions,r.revenue,r.profit])]),'text/csv;charset=utf-8');}catch(e){$('#ad-error').textContent=e.message;}};
$('#ad-record-csv').onclick=()=>download('広告入力-'+today()+'.csv',csv([['日付','LP','媒体','経路','広告費','表示','クリック','その他費用','送客総数','メモ'],...rowsFiltered().map(r=>[r.date,r.lp,r.medium,r.channel,r.spend,r.impressions,r.clicks,r.other,r.visits,r.note])]),'text/csv;charset=utf-8');
$('#ad-legacy-export').onclick=()=>download('Ad-Note-取込原本-'+today()+'.json',A.serialize(ads().records.filter(r=>r.legacy).map(r=>r.legacy)));
filter.onsubmit=e=>e.preventDefault();filter.onchange=draw;$('#ad-group').onchange=draw;$('#ad-sort').onchange=draw;
document.addEventListener('click',async e=>{try{const b=e.target.closest('button,a');if(!b)return;const d=b.dataset;if(d.adTab)selectTab(d.adTab);if(d.adClose)closeDialog(d.adClose);if(d.adPeriod){const day=today(),p=d.adPeriod,r=p==='all'?{start:'2000-01-01',end:day}:p==='previous'?F.range('month',F.shift('month',day,-1)):p==='month'?{start:day.slice(0,7)+'-01',end:day}:{start:p==='yesterday'?F.addDays(day,-1):day,end:p==='yesterday'?F.addDays(day,-1):day};filter.elements.start.value=r.start;filter.elements.end.value=r.end;draw();}if(d.adEdit)openRecord(d.adEdit);if(d.adCopy)openRecord(d.adCopy,true);if(d.adLead)openLead(d.adLead);if(d.adCustomer)openCustomer(d.adCustomer);if(d.adCase)window.dispatchEvent(new CustomEvent('crm-open-case',{detail:{id:d.adCase}}));
 if(d.adDelete){assertWrite();const w=draft(),r=w.ads.records.find(r=>r.id===d.adDelete);if(!r||!confirm(r.date+' / '+r.lp+' / '+money(r.spend)+' の広告実績を削除しますか？'+(r.legacy?' 取込原本も消えます。先にバックアップを保存してください。':'')))return;w.ads.records=w.ads.records.filter(r=>r.id!==d.adDelete);await saveWork(w,'広告実績を削除しました。');}if(d.adLeadDelete){assertWrite();const w=draft(),l=w.ads.leads.find(l=>l.id===d.adLeadDelete);if(!l||l.customerId)throw Error('顧客紐付け済みの送客は削除できません。');if(!confirm((l.name||l.id)+' の送客を削除しますか？'))return;w.ads.leads=w.ads.leads.filter(l=>l.id!==d.adLeadDelete);await saveWork(w,'送客を削除しました。');}
 }catch(err){$('#ad-error').textContent=err.message;notify(err.message);}});
$('#ad-add-record').onclick=()=>{try{openRecord();}catch(e){notify(e.message);}};$('#ad-add-lead').onclick=()=>{try{openLead();}catch(e){notify(e.message);}};$('#ad-add-customer').onclick=()=>{try{openLead('',true);}catch(e){notify(e.message);}};$('#ad-more-records').onclick=()=>{recordLimit+=50;renderRecords();};$('#ad-more-leads').onclick=()=>{journeyLimit+=50;renderJourneys();};$('#ad-sample').onclick=()=>{sample=!sample;selectTab('overview');};
// Existing CRM customer editor shares the same acquisition data.
const profile=document.createElement('div');profile.className='ad-fields';profile.innerHTML=`<label>LP<select name="adLP"></select></label><label>広告媒体<select name="adMedium"></select></label>${field('adDate','初回送客日','date',false)}`;$('#customer-profile-fields').append(profile);
function populateProfile(c){const f=$('#customer-form'),cat=G.catalog(customers,work()),s=G.customerSource(c,ads());for(const [name,key]of [['adLP','lp'],['adMedium','medium']]){f.elements[name].innerHTML=option('','未設定')+cat[key].map(v=>option(v)).join('');f.elements[name].value=s[key];}f.elements.adDate.value=G.acquiredDate(c);}
window.addEventListener('crm-customer-open',e=>{const c=customers.find(c=>c.id===e.detail.id);if(c)populateProfile(c);});
window.CRMAdsUI={profileValue(c,f){return {...(c.acquisition||{}),lp:f.elements.adLP.value,medium:f.elements.adMedium.value,date:f.elements.adDate.value};},syncCustomers(cs){let changed=false;const w=draft();for(const c of cs){const l=w.ads.leads.find(l=>l.id===c.acquisition?.leadId&&l.customerId===c.id);if(l){const n={...l,...G.source(c.acquisition),date:c.acquisition.date||l.date};if(JSON.stringify(n)!==JSON.stringify(l)){Object.assign(l,n);changed=true;}}}return changed?w:null;}};
const caseField=document.createElement('label');caseField.textContent='広告・送客の紐付け';const caseSelect=document.createElement('select');caseSelect.name='adLeadId';caseField.append(caseSelect);$('#fc-form-fields').append(caseField);
function caseOptions(cid,id=''){caseSelect.innerHTML=option('','顧客の初回流入を使う')+ads().leads.filter(l=>l.customerId===cid).map(l=>option(l.id,l.date+' / '+(l.lp||'LP未設定')+' / '+(l.medium||'媒体未設定'))).join('');caseSelect.value=id;}
window.addEventListener('crm-case-open',e=>{const a=customers.flatMap(c=>c.factoringCases||[]).find(a=>a.id===e.detail.id);caseOptions(e.detail.customerId,a?.adLeadId||'');});$('#fc-form').elements.customer.addEventListener('change',e=>caseOptions(e.target.value));
function crmSummary(){if(!['sales','reports'].includes(document.body.dataset.page))return;const id=document.body.dataset.page==='sales'?'mg-dashboard':'mg-report-section';let el=$('#ad-crm-summary');if(!el){el=document.createElement('section');el.id='ad-crm-summary';el.className='ad-summary';$('#'+id).append(el);}const t=G.analyze(customers,work(),{start:today().slice(0,7)+'-01',end:today()}).total;el.innerHTML='<div class="mg-heading"><h2>今月の広告・利益</h2><a href="advertising.html">広告を分析 →</a></div><div class="ad-kpis">'+cards(t)+'</div><p class="fc-note">案件の見込利益 '+money(t.grossProfit)+' − 広告費 '+money(t.spend)+' − 広告のその他費用 '+money(t.other)+'。上の案件利益へ広告費を再入力する必要はありません。</p>';}
window.addEventListener('crm-render',()=>{draw();crmSummary();});window.addEventListener('focus',()=>{draw();crmSummary();});
// New customer route is also directly available from the existing customer list.
if(document.body.dataset.page==='customers'){const b=document.createElement('a');b.href='advertising.html?tab=leads&new=customer';b.className='primary ad-new-customer';b.textContent='＋ 顧客を登録';$('.customer-panel').prepend(b);}
const q=new URLSearchParams(location.search);if(onPage){if(q.get('tab')==='leads')selectTab('leads');else draw();if(q.get('new')==='customer')openLead('',true);}crmSummary();
if(document.body.dataset.page==='cases'&&q.get('customer')&&customers.some(c=>c.id===q.get('customer'))){$('#fc-add').click();$('#fc-form').elements.customer.value=q.get('customer');caseOptions(q.get('customer'));}
})();
