'use strict';
(()=>{const M=window.CRMManagement;let bucket='late',analysisMode='month';const unit=n=>n+'人',num=n=>n+'件',money=n=>n===null?'—':yen(n);
const defs=[['count','買取件数',num],['purchase','実行買取額',money],['profit','見込利益',money],['recovery','回収額',money],['outstanding','未回収残高',money],['overdue','延滞金額',money],['overdueCount','延滞件数',num],['newCustomers','新規顧客数',unit],['repeatCustomers','リピート顧客数',unit],['avgPurchase','平均買取額',money],['avgProfit','平均利益額',money]];
const delta=(n,p)=>{if(n===null||p===null)return '前月比 —（対象なし）';const v=M.change(n,p);return v===null?'比較不可（前月0）':'前月比 '+(v>0?'＋':v<0?'−':'±')+Math.abs(v).toFixed(1)+'%';};
const card=(key,title,value,previous,format=money)=>`<div class="mg-kpi ${['outstanding','overdue','overdueCount'].includes(key)?'mg-stock':''}" data-kpi="${key}"><span>${title}</span><strong class="${value<0?'negative':''}">${format(value)}</strong><small>${delta(value,previous)}</small></div>`;
function summary(){const {now,previous}=M.comparison(),n=M.stats(customers,now.start,now.end),p=M.stats(customers,previous.start,previous.end);$('#mg-month-caption').textContent=now.start+' 〜 '+now.end+' ／ 比較：'+previous.start+' 〜 '+previous.end;const dueCount=customers.filter(c=>c.status!=='done'&&c.due&&c.due<=today()).length;const mainCard=(key,title,value,href,hint)=>`<a class="mg-kpi" data-kpi="${key}" href="${href}"><span>${title}</span><strong class="${key==='profit'&&n.profit<0?'negative':''}">${value}</strong><small>${hint} →</small></a>`;$('#mg-main-kpis').innerHTML=mainCard('today','今日対応する人',dueCount+'人','today.html','対応日超過も含む')+mainCard('overdueCount','回収期限超過',n.overdueCount+'件','recovery.html?bucket=late','期限を過ぎた未回収')+mainCard('outstanding','未回収額',yen(n.outstanding),'recovery.html?bucket=all','現在の残高')+mainCard('profit','今月の見込利益',yen(n.profit),'reports.html','買取済案件から集計');$('#mg-primary-comparison').innerHTML=card('overdueCount','回収期限超過',n.overdueCount,p.overdueCount,num)+card('outstanding','未回収額',n.outstanding,p.outstanding)+card('profit','今月の見込利益',n.profit,p.profit);$('#mg-other-kpis').innerHTML=card('fee','今月の売上相当・手数料見込',n.fee,p.fee)+defs.filter(d=>!['profit','outstanding','overdueCount'].includes(d[0])).map(([k,t,f])=>card(k,k==='overdue'?'現在の'+t:'今月の'+t,n[k],p[k],f)).join('');
 const tasks=customers.filter(c=>c.status!=='done'&&c.due&&c.due<=today()).sort((a,b)=>a.due.localeCompare(b.due));$('#mg-followup-title').textContent='今日までの顧客対応 '+tasks.length+'人';$('#mg-followups').innerHTML=tasks.slice(0,4).map(c=>`<div class="daily-followup ${c.due<today()?'is-overdue':'is-today'}"><button class="mg-followup" data-mg-customer="${esc(c.id)}"><strong>${esc(c.name)}</strong><span>${esc(c.next||'対応内容未設定')}</span><small>${c.due<today()?'対応日超過':'今日'} · ${esc(c.due)}</small></button>${CRMQuick.actions(c)}</div>`).join('')||'<p class="fc-note">今日までの対応予定はありません。</p>';}
function recoveryCards(rows){return ['late','today','soon'].map((k,i)=>{const group=rows.filter(r=>r.bucket===k);return `<a class="mg-due ${k}" href="recovery.html?bucket=${k}"><span>${['期限超過','本日期限','7日以内に期日'][i]}</span><strong>${group.length}件 <small>${yen(group.reduce((n,r)=>n+r.amount,0))}</small></strong></a>`}).join('');}
function recoveryRows(rows){return rows.map(r=>`<button class="mg-recovery-row ${r.bucket}" data-mg-case="${esc(r.id)}"><span><strong>${esc(r.name)}</strong><small>${esc(r.id)}</small></span><span class="mg-recovery-amount">${yen(r.amount)}</span><span>${r.days?'期限超過 '+r.days+'日':r.bucket==='today'?'本日期限':r.due}<small>期日 ${r.due}</small></span><span>${esc(r.owner)}</span><span aria-hidden="true">入金・詳細 →</span></button>`).join('')||'<p class="empty">該当する未回収案件はありません。</p>';}
function renderRecovery(){const rows=M.recovery(customers);$('#mg-recovery-summary').innerHTML=recoveryCards(rows);const urgent=rows.filter(r=>['late','today','soon'].includes(r.bucket));$('#mg-urgent-list').innerHTML=recoveryRows(urgent.slice(0,4));$('#mg-urgent-more').textContent=urgent.length>4?'残り'+(urgent.length-4)+'件も回収管理で確認 →':'回収管理で全件確認 →';$('#mg-recovery-filters').innerHTML=[['late','期限超過'],['today','本日期限'],['soon','7日以内'],['all','全未回収']].map(([k,l])=>`<button data-recovery-bucket="${k}" aria-pressed="${bucket===k}">${l} <b>${rows.filter(r=>k==='all'||r.bucket===k).length}</b></button>`).join('');$('#mg-recovery-list').innerHTML=recoveryRows(rows.filter(r=>bucket==='all'||r.bucket===bucket));$('#mg-recovery-total').textContent='全未回収 '+rows.length+'件 / '+yen(rows.reduce((n,r)=>n+r.amount,0));}
function groupTable(rows){return '<div class="numeric-scroll"><table class="fc-table"><thead><tr><th>区分</th><th>顧客</th><th>買取件数</th><th>買取額</th><th>売上相当</th><th>見込利益</th></tr></thead><tbody>'+rows.map(r=>`<tr><th>${esc(r.name)}</th><td>${r.customers}</td><td>${r.count}</td><td>${yen(r.purchase)}</td><td>${yen(r.fee)}</td><td class="${r.profit<0?'negative':''}">${yen(r.profit)}</td></tr>`).join('')+'</tbody></table></div>'+(rows.length?'':'<p class="fc-note">この期間の買取はありません。</p>');}
function renderAnalysis(){const {now,previous}=M.comparison(),start=analysisMode==='year'?today().slice(0,4)+'-01-01':now.start,a=M.analysis(customers,start,today()),p=M.stats(customers,previous.start,previous.end);$('#mg-analysis-range').textContent=start+' 〜 '+today();document.querySelectorAll('[data-mg-analysis]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mgAnalysis===analysisMode)));$('#mg-year-totals').innerHTML=['count','purchase','fee','profit','recovery'].map(k=>`<div class="mg-kpi"><span>${{count:'買取件数',purchase:'買取額',fee:'売上相当',profit:'見込利益',recovery:'回収額'}[k]}</span><strong>${k==='count'?num(a.totals[k]):yen(a.totals[k])}</strong></div>`).join('');const n=M.stats(customers,now.start,now.end);$('#mg-comparison-rows').innerHTML=[['fee','売上相当'],...defs.map(([k,t])=>[k,t])].map(([k,t])=>{const f=defs.find(d=>d[0]===k)?.[2]||money;return `<tr><th>${t}</th><td>${f(n[k])}</td><td>${f(p[k])}</td><td>${delta(n[k],p[k])}</td></tr>`}).join('');$('#mg-compare-caption').textContent='今月 '+now.start+'〜'+now.end+' ／ 前月 '+previous.start+'〜'+previous.end;$('#mg-ranking').innerHTML=a.ranking.map((c,i)=>`<button class="mg-rank-row" data-mg-customer="${esc(c.id)}"><span>${i+1}</span><strong>${esc(c.name)}</strong><span>${c.count}件</span><b class="${c.profit<0?'negative':''}">${yen(c.profit)}</b></button>`).join('')||'<p class="empty">この期間の買取はありません。</p>';$('#mg-owner-results').innerHTML=groupTable(a.owners);$('#mg-type-results').innerHTML=groupTable(a.types);$('#mg-channel-results').innerHTML=groupTable(a.channels);}
function profile(c){const s=M.customer(c);$('#mg-customer-totals').innerHTML=[['累計取引回数（買取）',num(s.purchases)],['累計買取額',yen(s.purchase)],['累計見込利益',yen(s.profit)],['未回収額',yen(s.outstanding)]].map(([l,v],i)=>`<div><span>${l}</span><strong class="${i===2&&s.profit<0?'negative':''}">${esc(v)}</strong></div>`).join('');$('#mg-customer-stats').innerHTML=[['初回申込日',s.firstApplication||'未登録'],['最終取引日（買取）',s.lastTrade||'未登録'],['累計申込回数',num(s.applications)],['延滞経験案件数',num(s.lateCount)],['最終連絡日',s.lastContact||'未記録'],['次回対応日',s.next||'未設定'],['流入経路',s.channel],['顧客ランク（手動）',M.ranks[s.rank]]].map(([l,v])=>`<div><span>${l}</span><strong>${esc(v)}</strong></div>`).join('');}
function fitMoney(){document.querySelectorAll('.mg-kpi>strong,.mg-due small').forEach(e=>{if(!e.getClientRects().length)return;e.style.fontSize='';let size=parseFloat(getComputedStyle(e).fontSize);while(e.scrollWidth>e.clientWidth&&size>11)e.style.fontSize=(--size)+'px';});}
function renderManagement(){summary();renderRecovery();renderAnalysis();fitMoney();if(selectedId){const c=customers.find(c=>c.id===selectedId);if(c)profile(c);}}
window.addEventListener('crm-customer-open',e=>{const c=customers.find(c=>c.id===e.detail.id);if(!c)return;profile(c);const f=$('#customer-form');f.elements.customerRank.value=M.customer(c).rank;f.elements.lastContactDate.value=c.lastContactDate||'';f.elements.lastContactDate.max=today();f.elements.acquisitionChannel.value=c.acquisition?.channel||'不明';});
$('#mg-contact-today').onclick=()=>{$('#customer-form').elements.lastContactDate.value=today();};
document.addEventListener('click',e=>{const customer=e.target.closest('[data-mg-customer]'),c=e.target.closest('[data-mg-case]'),filter=e.target.closest('[data-recovery-bucket]'),an=e.target.closest('[data-mg-analysis]');if(customer)openCustomer(customer.dataset.mgCustomer);if(c)window.dispatchEvent(new CustomEvent('crm-open-case',{detail:{id:c.dataset.mgCase}}));if(filter){bucket=filter.dataset.recoveryBucket;history.replaceState(null,'','recovery.html?bucket='+bucket);renderRecovery();}if(an){analysisMode=an.dataset.mgAnalysis;renderAnalysis();}});
const q=new URLSearchParams(location.search).get('bucket');if(['late','today','soon','all'].includes(q))bucket=q;
$('#mg-trends').addEventListener('toggle',()=>{if($('#mg-trends').open)window.dispatchEvent(new Event('resize'))});
window.addEventListener('resize',fitMoney);window.addEventListener('crm-render',renderManagement);window.addEventListener('focus',renderManagement);let asOf=today();setInterval(()=>{if(!document.hidden&&today()!==asOf){asOf=today();render();}},60000);renderManagement();
})();
