/* Browser-only workflow utilities. External systems are not connected. */
(function(root){'use strict';
const F=typeof module!=='undefined'&&module.exports?require('./finance.js'):root.CRMFinance;
const C=typeof module!=='undefined'&&module.exports?require('./factoring.js'):root.CRMFactoring;
const O=typeof module!=='undefined'&&module.exports?require('./operations.js'):root.CRMOperations;
const channels=['不明','LINE自然流入','広告','紹介','その他'];
const defaults=()=>({version:5,bankRows:[],jobs:[],budgets:{},cash:{balance:null,date:'',ratio:100},expenses:[],history:[]});
function workflow(c){return c.workflow||{documents:[],contract:{status:'draft',reference:'',due:'',signedDate:'',memo:''},funding:{date:'',amount:0,cost:0}};}
const allCases=customers=>customers.flatMap(c=>(c.factoringCases||[]).map(a=>({...a,customerId:c.id,customerName:c.name})));
function date(s,future=true){F.parse(s);if(s<'2000-01-01'||s>'2100-12-31'||!future&&s>F.today())throw Error('日付を確認してください（2000〜2100年、実績は今日まで）。');return s;}
const text=(v,max=1000)=>{if(typeof v!=='string'||v.length>max)throw Error('文字列の形式または長さを確認してください。');return v;};
function validateWorkflow(w){if(!w||!Array.isArray(w.documents)||w.documents.length>30)throw Error('書類リストを確認してください。');
 const seen=new Set();for(const d of w.documents){text(d.id,100);if(!/^[A-Za-z0-9_-]+$/.test(d.id))throw Error('書類IDを確認してください。');if(seen.has(d.id))throw Error('書類IDが重複しています。');seen.add(d.id);if(!text(d.name,100).trim())throw Error('書類名を入力してください。');if(!['missing','received','checked','returned','waived'].includes(d.status))throw Error('書類状態が不正です。');if(d.due)date(d.due);if(d.file){text(d.file.name,160);if(!['application/pdf','image/png','image/jpeg'].includes(d.file.type)||typeof d.file.data!=='string'||d.file.data.length>700000||!/^[A-Za-z0-9+/]*={0,2}$/.test(d.file.data))throw Error('添付は500KB以下のPDF・PNG・JPEGにしてください。');if(!(d.file.type==='application/pdf'?d.file.data.startsWith('JVBERi0'):d.file.type==='image/png'?d.file.data.startsWith('iVBORw0KGgo'):d.file.data.startsWith('/9j/')))throw Error('添付データの形式が一致しません。');}}
 const c=w.contract;if(!c||!['draft','sent','signed','cancelled'].includes(c.status))throw Error('契約状況を確認してください。');text(c.reference,100);text(c.memo,1000);if(c.due)date(c.due);if(c.status==='signed'){date(c.signedDate,false);}else if(c.signedDate)throw Error('署名完了日と状態を確認してください。');
 if(!w.funding)throw Error('先払い予定を確認してください。');if(w.funding.date)date(w.funding.date);F.amount(w.funding.amount);F.amount(w.funding.cost);return w;
}
function parseCSV(input){if(input.length>2000000)throw Error('CSVは2MB以内にしてください。');const src=input.replace(/^\uFEFF/,'');let rows=[],row=[],cell='',quoted=false,closed=false;
 for(let i=0;i<src.length;i++){const x=src[i];if(quoted){if(x==='"'){if(src[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=x;continue;}
 if(closed&&x!==','&&x!=='\r'&&x!=='\n')throw Error('CSVの引用符を確認してください。');
 if(x==='"'){if(cell.length||closed)throw Error('CSVの引用符を確認してください。');quoted=true;}else if(x===','){row.push(cell);cell='';closed=false;}else if(x==='\n'||x==='\r'){if(x==='\r'&&src[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';closed=false;}else cell+=x;
 }if(quoted)throw Error('CSVの引用符が閉じていません。');if(cell.length||row.length||closed){row.push(cell);if(row.some(v=>v!==''))rows.push(row);}if(rows.length<2)throw Error('CSVに明細がありません。');const required=['明細ID','入金日','入金額','振込名義'],head=rows.shift().map(s=>s.trim());if(required.some(k=>head.filter(v=>v===k).length!==1))throw Error('列名は「明細ID,入金日,入金額,振込名義」が必要です。');
 if(rows.length>1000)throw Error('一度に取り込める明細は1000件までです。');const ids=new Set();return rows.map((r,i)=>{if(r.length!==head.length)throw Error((i+2)+'行目の列数を確認してください。');const v=k=>r[head.indexOf(k)].trim();let amount=v('入金額');if(amount.includes(',')){if(!/^\d{1,3}(,\d{3})+$/.test(amount))throw Error('金額の桁区切りを確認してください。');amount=amount.replaceAll(',','');}const b={id:v('明細ID'),date:v('入金日'),amount:F.amount(amount),payer:v('振込名義')};validateBank(b);if(ids.has(b.id))throw Error('CSV内で明細IDが重複しています。');ids.add(b.id);return b;});
}
function validateBank(b){if(!text(b.id,100).trim()||!text(b.payer,160).trim())throw Error('明細IDと振込名義を入力してください。');date(b.date,false);if(!F.amount(b.amount))throw Error('入金額は1円以上にしてください。');return b;}
function mergeBank(existing,incoming){const map=new Map(existing.map(b=>[b.id,b]));let added=0,skipped=0;for(const b of incoming){const old=map.get(b.id);if(old){if(old.date!==b.date||old.amount!==b.amount||old.payer!==b.payer)throw Error('同じ明細IDで内容が異なります：'+b.id);skipped++;}else{map.set(b.id,b);added++;}}return {rows:[...map.values()],added,skipped};}
function bankLinks(customers){const map=new Map();for(const c of allCases(customers))if(!c.void)for(const r of c.receipts||[])if(!r.void&&r.bankRowId){if(map.has(r.bankRowId))throw Error('同じ銀行明細が複数の入金に紐付いています。');map.set(r.bankRowId,{caseId:c.id,customerId:c.customerId,receipt:r});}return map;}
function checkLog(list){if(!Array.isArray(list)||list.length>10000)throw Error('履歴の形式を確認してください。');for(const h of list){text(h.text,30000);if(!Number.isFinite(Date.parse(h.at)))throw Error('履歴の日付が不正です。');}}
function validateCustomers(customers,work){if(!Array.isArray(customers)||customers.length>2000)throw Error('顧客データの形式を確認してください。');const ids=new Set(),caseIds=new Set(),receiptIds=new Set();let attachmentChars=0;
 for(const c of customers){if(!text(c.id,100)||ids.has(c.id))throw Error('顧客IDが重複しています。');ids.add(c.id);if(c.customerRank!==undefined&&!['good','normal','watch'].includes(c.customerRank))throw Error('顧客ランクが不正です。');if(c.lastContactDate)date(c.lastContactDate,false);text(c.name,160);if(c.phone!==undefined)text(c.phone,40);if(c.lineName!==undefined)text(c.lineName,160);text(c.owner,100);text(c.next,500);text(c.due,10);if(!['new','active','waiting','done'].includes(c.status)||!Array.isArray(c.history))throw Error('顧客の状態・履歴を確認してください。');for(const h of c.history){text(h.text,30000);if(!Number.isFinite(Date.parse(h.at)))throw Error('履歴の日付が不正です。');}
 for(const t of c.transactions||[])F.validate(t);for(const n of c.legalNotices||[]){O.validateNotice(n);text(n.id,100);checkLog(n.history);}
 if(c.acquisition&&!channels.includes(c.acquisition.channel))throw Error('集客経路が不正です。');
 for(const a of c.factoringCases||[]){if(!a.id||caseIds.has(a.id))throw Error('案件IDが重複しています。');caseIds.add(a.id);C.validate(a);checkLog(a.history||[]);if(a.workflow){validateWorkflow(a.workflow);for(const d of a.workflow.documents)attachmentChars+=d.file?.data?.length||0;}for(const r of a.receipts){if(receiptIds.has(r.id))throw Error('入金IDが重複しています。');receiptIds.add(r.id);}}
 }if(attachmentChars>2800000)throw Error('添付の合計が上限（約2MB）を超えています。不要な添付を外してください。');const links=bankLinks(customers);if(work)for(const [id,link]of links){const b=work.bankRows.find(b=>b.id===id);if(!b||b.date!==link.receipt.date||b.amount!==link.receipt.amount)throw Error('銀行明細と照合済み入金の内容が一致しません。');}return customers;
}
function validateWork(w){if(!w||w.version!==5||!Array.isArray(w.bankRows)||!Array.isArray(w.jobs)||!Array.isArray(w.expenses)||!Array.isArray(w.history)||!w.budgets||!w.cash)throw Error('業務データの形式が違います。');if(w.bankRows.length>5000||w.jobs.length>2000)throw Error('デモの件数上限を超えています。');const ids=new Set();for(const b of w.bankRows){validateBank(b);if(ids.has(b.id))throw Error('明細IDが重複しています。');ids.add(b.id);}checkLog(w.history);const events=new Set(),jobIds=new Set();for(const j of w.jobs){if(!text(j.id,100)||jobIds.has(j.id))throw Error('引継ぎIDが重複しています。');jobIds.add(j.id);if(!text(j.eventId,100).trim()||events.has(j.eventId))throw Error('受付IDが重複しています。');events.add(j.eventId);text(j.title,160);text(j.owner,80);text(j.note,1000);if(!['waiting','working','done'].includes(j.status)||!['manual','demo'].includes(j.source))throw Error('引継ぎ状態が不正です。');if(j.due)date(j.due);if(j.status==='done'&&!j.note.trim())throw Error('完了時は対応結果を記録してください。');}
 if(w.cash.balance!==null)F.amount(w.cash.balance);if(w.cash.date)date(w.cash.date,false);if(!Number.isInteger(w.cash.ratio)||w.cash.ratio<0||w.cash.ratio>100)throw Error('回収想定は0〜100%にしてください。');for(const x of w.expenses){date(x.date);F.amount(x.amount);text(x.memo,200);}for(const k of Object.keys(w.budgets)){if(!channels.includes(k))throw Error('集客経路を確認してください。');F.amount(w.budgets[k]);}return w;}
function forecast(customers,work,asOf=F.today()){
 if(work.cash.balance===null||work.cash.date!==asOf)return {ready:false};const cs=allCases(customers).filter(c=>!c.void),days=Array.from({length:31},(_,i)=>({date:F.addDays(asOf,i),incoming:0,outgoing:0,balance:0})),map=new Map(days.map(d=>[d.date,d]));
 for(const c of cs){if(c.status==='purchased'&&map.has(c.dueDate))map.get(c.dueDate).incoming+=Math.floor(Math.max(0,c.invoiceAmount-C.paid(c,asOf))*work.cash.ratio/100);
 const p=workflow(c).funding;if(c.status==='approved'&&p.date&&map.has(p.date))map.get(p.date).outgoing+=p.amount+p.cost;}
 for(const x of work.expenses)if(map.has(x.date))map.get(x.date).outgoing+=x.amount;
 let balance=work.cash.balance;for(const d of days){balance+=d.incoming-d.outgoing;d.balance=balance;}
 return {ready:true,days,minimum:Math.min(work.cash.balance,...days.map(d=>d.balance)),end:balance,overdue:cs.filter(c=>c.status==='purchased'&&c.dueDate<asOf).reduce((n,c)=>n+c.invoiceAmount-C.paid(c,asOf),0),unplanned:cs.filter(c=>c.status==='approved'&&!workflow(c).funding.date).length,missedPlans:cs.filter(c=>c.status==='approved'&&workflow(c).funding.date&&workflow(c).funding.date<asOf).length};
}
function reminders(customers,work,asOf=F.today()){const out=[];for(const c of customers){if(c.status!=='done'&&c.due&&c.due<=asOf)out.push({kind:'顧客対応',title:c.name+'：'+c.next,date:c.due,customerId:c.id});for(const a of c.factoringCases||[]){if(a.void)continue;const w=workflow(a);for(const d of w.documents)if(['missing','returned'].includes(d.status)&&d.due&&d.due<=asOf)out.push({kind:'書類',title:c.name+'：'+d.name,date:d.due,caseId:a.id});if(['draft','sent'].includes(w.contract.status)&&w.contract.due&&w.contract.due<=asOf)out.push({kind:'契約',title:c.name+'：契約の確認',date:w.contract.due,caseId:a.id});if(a.status==='purchased'&&a.dueDate<=asOf&&C.paid(a)<a.invoiceAmount)out.push({kind:'回収',title:c.name+'：未回収 '+(a.invoiceAmount-C.paid(a))+'円',date:a.dueDate,caseId:a.id});}}
 for(const j of work.jobs)if(j.status!=='done'&&j.due&&j.due<=asOf)out.push({kind:'引継ぎ',title:j.title,date:j.due,jobId:j.id});return out.sort((a,b)=>a.date.localeCompare(b.date));}
function acquisition(customers,work){return channels.map(channel=>{const cs=customers.filter(c=>(c.acquisition?.channel||'不明')===channel),cases=allCases(cs).filter(c=>!c.void);const bought=cases.filter(c=>c.status==='purchased');return {channel,customers:cs.length,cases:cases.length,contracts:cases.filter(c=>workflow(c).contract.status==='signed').length,purchases:bought.length,fee:bought.reduce((n,c)=>n+c.invoiceAmount-c.purchaseAmount,0),budget:work.budgets[channel]||0};});}
function parseBackup(raw){if(raw.length>12000000)throw Error('バックアップは12MB以内にしてください。');const b=JSON.parse(raw,(key,value)=>{if(['__proto__','prototype','constructor'].includes(key))throw Error('不正なキーが含まれています。');return value;});if(b.format!=='osanai-crm-backup'||b.version!==5)throw Error('この管理画面のv5バックアップを選択してください。');validateWork(b.work);validateCustomers(b.customers,b.work);return b;}
const api={channels,defaults,workflow,allCases,date,validateWorkflow,parseCSV,mergeBank,validateBank,bankLinks,validateCustomers,validateWork,forecast,reminders,acquisition,parseBackup};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.CRMWorkflow=api;
})(typeof window==='undefined'?globalThis:window);
