'use strict';
(()=>{const W=window.CRMWorkflow,S=window.CRMWorkbench,C=window.CRMFactoring;let selectedCase=null,draftDocs=[],caseClean='',jobId=null,jobClean='',bankPreview=null,backupPreview=null;
const docLabels={missing:'未提出',received:'受領',checked:'確認済',returned:'差戻し',waived:'対象外'},contractLabels={draft:'作成中',sent:'署名待ち',signed:'署名完了',cancelled:'取消'};
const cases=()=>W.allCases(customers),getCase=id=>cases().find(c=>c.id===id);
const clone=x=>JSON.parse(JSON.stringify(x));
const openTool=id=>{const d=$('#wb-'+id);d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'});if(id==='cash')renderCash()};
const download=(name,data,type='application/json')=>{const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)};
async function logWork(next,message){next.history=[...(next.history||[]),{at:stamp(),text:message}];await S.saveWork(next);renderWorkbench();}
async function mutateCase(id,fn,message){const target=getCase(id);if(!target)throw Error('案件が見つかりません。');const next=customers.map(c=>c.id===target.customerId?{...c,factoringCases:c.factoringCases.map(a=>a.id===id?{...fn(clone(a)),history:[...(a.history||[]),{at:stamp(),text:message}]}:a),history:[...c.history,{at:stamp(),text:id+'：'+message}]}:c);if(!await persist(next))return false;render();refreshCustomerAfterSale();return true;}
function renderWorkbench(){
 const state=S.state,cs=cases().filter(c=>!c.void),tasks=W.reminders(customers,state);
 $('#wb-storage-alert').hidden=!S.blocked&&!S.locked;$('#wb-storage-alert').textContent=S.blocked||(S.locked?'書込ロック中：保存操作は停止しています。解除は「保存・バックアップ」から。':'');$('#wb-lock').checked=S.locked;
 $('#wb-reminder-count').textContent=tasks.length;
 $('#wb-document-list').innerHTML=cs.length?cs.map(c=>{const w=W.workflow(c),missing=w.documents.filter(d=>['missing','returned'].includes(d.status)).length;return `<button class="fc-case" data-wb-case="${esc(c.id)}"><strong>${esc(c.customerName)}</strong><small>${esc(c.id)} · ${esc(c.reference||'請求書番号未入力')}</small><p>書類 ${w.documents.length}項目 / 未提出・差戻し ${missing}</p><span class="fc-tag">契約：${contractLabels[w.contract.status]}</span><span class="fc-open">書類・契約・先払い予定 →</span></button>`}).join(''):'<p class="empty">先に手動管理から申込案件を登録してください。</p>';
 renderBank();renderCash();renderJobs();renderAcquisition();
 renderReminders();
 $('#wb-audit').innerHTML=state.history.slice().reverse().slice(0,100).map(h=>`<p><small>${esc(timeLabel(h.at))}</small><br>${esc(h.text)}</p>`).join('')||'<p class="fc-note">業務設定を変更すると記録されます。</p>';
}
function renderReminders(){const tasks=W.reminders(customers,S.state);$('#wb-reminder-count').textContent=tasks.length;
 $('#wb-reminders-list').innerHTML=tasks.length?tasks.map(t=>`<button class="wb-reminder" ${t.caseId?'data-reminder-case="'+esc(t.caseId)+'"':t.customerId?'data-reminder-customer="'+esc(t.customerId)+'"':'data-reminder-job="'+esc(t.jobId)+'"'}><span class="fc-tag ${t.date<today()?'fc-alert':''}">${esc(t.kind)} · ${t.date<today()?'期限超過':'今日'}</span><strong>${esc(t.title)}</strong><small>${esc(t.date)} →</small></button>`).join(''):'<p class="empty">今日までの未完了項目はありません。</p>';
}
function collectDocs(){return draftDocs.map(d=>{const row=document.querySelector('[data-doc-row="'+d.id+'"]');return {...d,name:row.querySelector('[data-doc-name]').value.trim(),status:row.querySelector('[data-doc-status]').value,due:row.querySelector('[data-doc-due]').value}});}
function editorState(){return JSON.stringify({fields:[...new FormData($('#wb-case-form')).entries()],docs:collectDocs()});}
function renderDocFields(){
 $('#wb-doc-fields').innerHTML=draftDocs.map(d=>`<div class="wb-document" data-doc-row="${esc(d.id)}"><label>書類名<input data-doc-name maxlength="100" value="${esc(d.name)}" required></label><div class="field-grid"><label>状態<select data-doc-status>${Object.entries(docLabels).map(([k,v])=>`<option value="${k}" ${d.status===k?'selected':''}>${v}</option>`).join('')}</select></label><label>提出期限<input data-doc-due type="date" value="${esc(d.due)}"></label></div><div class="wb-toolbar"><label class="wb-file-label">添付（PDF・画像）<input type="file" data-doc-file accept="application/pdf,image/png,image/jpeg"></label>${d.file?`<span class="fc-note">${esc(d.file.name)}</span><button type="button" data-doc-download="${esc(d.id)}" class="fc-secondary">添付を保存</button><button type="button" data-doc-clear="${esc(d.id)}" class="fc-secondary">添付を外す</button>`:''}<button type="button" data-doc-remove="${esc(d.id)}" class="fc-secondary">項目を削除</button></div></div>`).join('')||'<p class="fc-note">書類項目は未設定です。「書類項目を追加」から業務に必要なものを登録できます。</p>';
}
function openCaseEditor(id){const c=getCase(id);if(!c||c.void)return;selectedCase=id;const w=clone(W.workflow(c)),f=$('#wb-case-form');f.reset();draftDocs=w.documents;renderDocFields();f.elements.contractStatus.value=w.contract.status;f.elements.contractRef.value=w.contract.reference;f.elements.contractDue.value=w.contract.due;f.elements.signedDate.value=w.contract.signedDate;f.elements.signedDate.max=today();f.elements.contractMemo.value=w.contract.memo;f.elements.fundingDate.value=w.funding.date;f.elements.fundingAmount.value=w.funding.amount;f.elements.fundingCost.value=w.funding.cost;syncContract();$('#wb-case-info').textContent=c.customerName+' / '+c.id+' / '+C.state(c);$('#wb-case-error').textContent='';caseClean=editorState();$('#wb-case-dialog').showModal();}
function syncContract(){const f=$('#wb-case-form');f.elements.signedDate.required=f.elements.contractStatus.value==='signed';f.elements.signedDate.disabled=f.elements.contractStatus.value!=='signed';}
$('#wb-case-form').elements.contractStatus.onchange=syncContract;
function closeCaseEditor(){if(editorState()!==caseClean&&!confirm('書類・契約の未保存の変更を破棄しますか？'))return;$('#wb-case-dialog').close();}
$('#wb-case-close').onclick=closeCaseEditor;$('#wb-case-dialog').addEventListener('cancel',e=>{e.preventDefault();closeCaseEditor()});
$('#wb-doc-add').onclick=()=>{draftDocs=collectDocs();if(draftDocs.length>=30){notify('書類は1案件30項目までです。');return;}draftDocs.push({id:crypto.randomUUID(),name:'',status:'missing',due:'',file:null});renderDocFields();};
$('#wb-doc-fields').onchange=async e=>{if(!e.target.matches('[data-doc-file]'))return;const file=e.target.files?.[0];if(!file)return;try{if(S.locked)throw Error('書込ロック中です。');if(file.size>500000||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw Error('500KB以下のPDF・PNG・JPEGを選択してください。');const bytes=new Uint8Array(await file.arrayBuffer());const valid=file.type==='application/pdf'?String.fromCharCode(...bytes.slice(0,5))==='%PDF-':file.type==='image/png'?bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71:bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)throw Error('ファイル内容と拡張子が一致していません。');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.slice(i,i+8192));const id=e.target.closest('[data-doc-row]').dataset.docRow;draftDocs=collectDocs().map(d=>d.id===id?{...d,file:{name:file.name,type:file.type,data:btoa(binary)},status:d.status==='missing'?'received':d.status}:d);renderDocFields();notify('添付を準備しました。下の保存ボタンで確定してください。');}catch(err){$('#wb-case-error').textContent=err.message;e.target.value='';}};
$('#wb-doc-fields').onclick=e=>{const remove=e.target.closest('[data-doc-remove]'),clear=e.target.closest('[data-doc-clear]'),dl=e.target.closest('[data-doc-download]');if(!remove&&!clear&&!dl)return;draftDocs=collectDocs();if(dl){const f=draftDocs.find(d=>d.id===dl.dataset.docDownload)?.file;if(f)download(f.name,new Blob([Uint8Array.from(atob(f.data),c=>c.charCodeAt(0))],{type:f.type}));return;}const targetDoc=draftDocs.find(d=>d.id===(remove?.dataset.docRemove||clear?.dataset.docClear));if(!confirm(`${targetDoc?.name||'名称未設定の書類'}\n${remove?'この書類項目と添付を外しますか？':'この添付を外しますか？'} 保存すると反映されます。`))return;if(remove)draftDocs=draftDocs.filter(d=>d.id!==remove.dataset.docRemove);else draftDocs=draftDocs.map(d=>d.id===clear.dataset.docClear?{...d,file:null}:d);renderDocFields();};
$('#wb-case-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,c=getCase(selectedCase);try{const w={documents:collectDocs(),contract:{status:f.elements.contractStatus.value,reference:f.elements.contractRef.value.trim(),due:f.elements.contractDue.value,signedDate:f.elements.contractStatus.value==='signed'?f.elements.signedDate.value:'',memo:f.elements.contractMemo.value.trim()},funding:{date:f.elements.fundingDate.value,amount:F.amount(f.elements.fundingAmount.value||0),cost:F.amount(f.elements.fundingCost.value||0)}};W.validateWorkflow(w);if(w.funding.date&&(!w.funding.amount||w.funding.amount>c.invoiceAmount))throw Error('先払い予定額は1円以上、請求書額面以下にしてください。');if(!w.funding.date&&(w.funding.amount||w.funding.cost))throw Error('先払い予定額を入力した場合は予定日も設定してください。');if(await mutateCase(c.id,a=>({...a,workflow:w}),`書類・契約・予定を更新：書類${w.documents.length}件 / 契約${contractLabels[w.contract.status]} / 予定${w.funding.date||'なし'} ${yen(w.funding.amount)}`)){caseClean=editorState();$('#wb-case-error').textContent='';notify('書類・契約・予定を保存しました。');}}catch(err){$('#wb-case-error').textContent=err.message;}};
$('#wb-contract-export').onclick=()=>{const c=getCase(selectedCase),w=W.workflow(c),lines=['契約確認メモ（契約書・電子署名ではありません）','出力日：'+today(),'顧客：'+c.customerName,'案件ID：'+c.id,'請求書番号：'+(c.reference||'未記入'),'売掛先：'+(c.debtor||'未記入'),'請求書額面：'+yen(c.invoiceAmount),'希望買取額：'+yen(c.requestedAmount),'実行買取額：'+yen(c.purchaseAmount),'契約管理番号：'+(w.contract.reference||'未記入'),'状態：'+contractLabels[w.contract.status],'署名完了日（手入力）：'+(w.contract.signedDate||'未記録'),'確認メモ：'+w.contract.memo,'このメモだけで契約が締結されたことにはなりません。'];download('契約確認メモ-'+c.id+'.txt',lines.join('\n'),'text/plain;charset=utf-8')};
// Large imports must not create every row × every case as duplicate option nodes.
let bankCandidates=new Map();
const bankOptions=targets=>targets.map(c=>`<option value="${esc(c.id)}">${esc(c.customerName)} / ${esc(c.id)} / 未回収額${yen(c.remaining)}</option>`).join('');
function prepareBankSelect(select){if(!select?.matches('[data-bank-target]')||select.dataset.ready)return;const targets=bankCandidates.get(select.closest('[data-bank-row]').dataset.bankRow)||[];select.insertAdjacentHTML('beforeend',bankOptions(targets));select.dataset.ready='true';}
for(const event of ['focusin','pointerdown','touchstart'])$('#wb-bank-list').addEventListener(event,e=>prepareBankSelect(e.target));
function renderBank(){const list=S.state.bankRows,links=W.bankLinks(customers);$('#wb-bank-count').textContent=`取込 ${list.length}件 / 照合済 ${list.filter(b=>links.has(b.id)).length}件 / 未照合 ${list.filter(b=>!links.has(b.id)).length}件`;
 const all=cases(),byId=new Map(all.map(c=>[c.id,c])),eligible=all.filter(c=>!c.void&&c.status==='purchased').map(c=>({...c,remaining:c.invoiceAmount-C.paid(c)})).filter(c=>c.remaining>0),defer=list.length*eligible.length>5000,groups=new Map();bankCandidates=new Map();
 $('#wb-bank-list').innerHTML=list.slice().reverse().map(b=>{const link=links.get(b.id),c=link?byId.get(link.caseId):null,key=b.date+'|'+b.amount;let targets=[];if(!link){if(!groups.has(key))groups.set(key,eligible.filter(c=>b.date>=c.purchaseDate&&b.amount<=c.remaining).sort((a,c)=>Number(c.remaining===b.amount)-Number(a.remaining===b.amount)));targets=groups.get(key);bankCandidates.set(b.id,targets);}return `<article class="wb-bank-row" data-bank-row="${esc(b.id)}"><strong>${esc(b.date)} · ${yen(b.amount)}</strong><p>${esc(b.payer)} <small>明細 ${esc(b.id)}</small></p>${link?`<span class="fc-tag">照合済：${esc(c?.customerName||'')} / ${esc(link.caseId)}</span><button class="fc-secondary" data-bank-unlink="${esc(b.id)}">照合を取消</button>`:`<label>反映する案件（候補は金額・日付だけで抽出）<select data-bank-target ${defer?'':'data-ready="true"'}><option value="">案件を確認して選択</option>${defer?'':bankOptions(targets)}</select></label><button class="primary" data-bank-match="${esc(b.id)}">確認して入金へ反映</button>${!targets.length?'<p class="fc-note">候補がありません。金額・買取日・未回収額を確認してください。</p>':''}`}</article>`}).join('')||'<p class="empty">CSVの明細を取り込むと表示されます。</p>';
}
$('#wb-bank-template').onclick=()=>download('入金CSV見本.csv','\uFEFF明細ID,入金日,入金額,振込名義\r\nSAMPLE-BANK-001,'+today()+',50000,サンプル商事\r\n','text/csv;charset=utf-8');
$('#wb-bank-file').onchange=async e=>{bankPreview=null;$('#wb-bank-preview').hidden=true;$('#wb-bank-import').hidden=true;try{const f=e.target.files?.[0];if(!f)return;const rows=W.parseCSV(await f.text()),merged=W.mergeBank(S.state.bankRows,rows);bankPreview=rows;$('#wb-bank-preview').textContent=`${rows.length}件を確認。新規 ${merged.added}件 / 同一IDで同内容 ${merged.skipped}件は追加しません。`;$('#wb-bank-preview').hidden=false;$('#wb-bank-import').hidden=false;$('#wb-bank-error').textContent='';}catch(err){$('#wb-bank-error').textContent=err.message;}e.target.value='';};
$('#wb-bank-import').onclick=async ()=>{try{if(!bankPreview)return;const merged=W.mergeBank(S.state.bankRows,bankPreview);await logWork({...clone(S.state),bankRows:merged.rows},`銀行CSV取込：追加${merged.added}件 / 重複${merged.skipped}件を除外`);bankPreview=null;$('#wb-bank-preview').hidden=true;$('#wb-bank-import').hidden=true;$('#wb-bank-error').textContent='';notify('明細を取り込みました。入金への反映は案件を確認して確定してください。');}catch(err){$('#wb-bank-error').textContent=err.message;}};
$('#wb-bank-list').onclick=async e=>{const match=e.target.closest('[data-bank-match]'),un=e.target.closest('[data-bank-unlink]');if(!match&&!un)return;try{const id=match?.dataset.bankMatch||un.dataset.bankUnlink,b=S.state.bankRows.find(b=>b.id===id),links=W.bankLinks(customers);if(match){if(links.has(id))throw Error('この明細は既に照合済みです。');const target=match.closest('[data-bank-row]').querySelector('[data-bank-target]').value,c=getCase(target);if(!c||c.void||c.status!=='purchased')throw Error('入金する案件を選択してください。');if(!confirm(`${c.customerName} / ${c.id} に ${yen(b.amount)} の入金を記録しますか？`))return;const r={id:'RC-'+crypto.randomUUID(),date:b.date,amount:b.amount,memo:'銀行CSV照合：'+b.payer,bankRowId:b.id,void:false};const next={...c,receipts:[...c.receipts,r]};C.validate(next);if(await mutateCase(c.id,a=>({...a,receipts:next.receipts}),'銀行入金照合：'+b.id+' / '+yen(b.amount)))notify('入金へ反映しました。');}else{const link=links.get(id);if(!link)return;if(!confirm('照合入金を取消し、明細を未照合へ戻しますか？ 履歴は残ります。'))return;if(await mutateCase(link.caseId,a=>({...a,receipts:a.receipts.map(r=>r.id===link.receipt.id?{...r,void:true}:r)}),'銀行入金照合を取消：'+id))notify('照合を取消しました。');}$('#wb-bank-error').textContent='';}catch(err){$('#wb-bank-error').textContent=err.message;}};
function renderCash(){const work=S.state,r=W.forecast(customers,work);if(document.activeElement?.closest('#wb-cash-form')===null){$('#wb-cash-form').elements.balance.value=work.cash.balance??'';$('#wb-cash-form').elements.ratio.value=work.cash.ratio;}
 if(!r.ready){$('#wb-cash-results').innerHTML=`<p class="wb-alert">${work.cash.date?'残高基準日が'+esc(work.cash.date)+'です。本日の残高を設定し直してください。':'本日の口座残高を設定すると、31日分の予定残高が表示されます。'}</p>`;}else{const min=Math.min(0,work.cash.balance,...r.days.map(d=>d.balance)),max=Math.max(1,work.cash.balance,...r.days.map(d=>d.balance)),y=v=>15+(max-v)/(max-min)*130,points=r.days.map((d,i)=>`${15+i*17},${y(d.balance)}`).join(' ');$('#wb-cash-results').innerHTML=`<div class="fc-metrics">${tile('期間末の予定残高',yen(r.end))}${tile('期間中の最低予定残高',yen(r.minimum))}${tile('予定に含めない延滞額',yen(r.overdue))}</div><p class="${r.minimum<0?'wb-alert':'fc-note'}">${r.minimum<0?'予定上、残高がマイナスになる日があります。':'入力された予定では、期間中の残高はマイナスになりません。'} 未設定の承認案件 ${r.unplanned}件 / 予定日超過 ${r.missedPlans}件。いずれも予定支出に含まれていません。</p><svg class="wb-cash-chart" viewBox="0 0 540 170" role="img" aria-label="31日分の予定残高。詳しい金額は数値表で確認できます。"><line x1="15" y1="${y(0)}" x2="525" y2="${y(0)}" stroke="#c2cfc6"/><polyline points="${points}" fill="none" stroke="#237c60" stroke-width="3"/><text x="15" y="164" font-size="11">${r.days[0].date}</text><text x="435" y="164" font-size="11">${r.days.at(-1).date}</text></svg><details class="fc-definitions"><summary>日別の予定残高を見る</summary><div class="numeric-scroll"><table class="fc-table"><thead><tr><th>日付</th><th>回収予定</th><th>支出予定</th><th>予定残高</th></tr></thead><tbody>${r.days.map(d=>`<tr><th>${d.date}</th><td>${yen(d.incoming)}</td><td>${yen(d.outgoing)}</td><td>${yen(d.balance)}</td></tr>`).join('')}</tbody></table></div></details>`;}
 $('#wb-expenses').innerHTML=work.expenses.map(x=>`<p>${esc(x.date)} ${yen(x.amount)} ${esc(x.memo)} <button class="fc-secondary" data-expense-remove="${esc(x.id)}">削除</button></p>`).join('');}
const tile=(name,value)=>`<div><span>${name}</span><strong>${value}</strong></div>`;
$('#wb-cash-form').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget,next=clone(S.state);next.cash={balance:F.amount(f.elements.balance.value),date:today(),ratio:Number(f.elements.ratio.value)};await logWork(next,'資金繰りの残高・回収想定を更新');notify('予定を更新しました。');}catch(err){notify(err.message);}};
$('#wb-expense-form').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget,next=clone(S.state),amount=F.amount(f.elements.amount.value);if(!amount)throw Error('支出は1円以上で入力してください。');next.expenses.push({id:crypto.randomUUID(),date:f.elements.date.value,amount,memo:f.elements.memo.value.trim()});await logWork(next,'その他支出予定を追加');f.reset();notify('支出予定を保存しました。');}catch(err){notify(err.message);}};
$('#wb-expenses').onclick=async e=>{const b=e.target.closest('[data-expense-remove]');if(!b)return;const item=S.state.expenses.find(x=>x.id===b.dataset.expenseRemove);if(!item||!confirm(`この支出予定を削除しますか？\n${item.date} / ${yen(item.amount)}\n${item.memo}\n削除後は予定残高にも反映されます。`))return;try{await logWork({...clone(S.state),expenses:S.state.expenses.filter(x=>x.id!==b.dataset.expenseRemove)},'その他支出予定を削除');notify('支出予定を削除しました。');}catch(err){notify(err.message);}};
function renderJobs(){$('#wb-jobs-list').innerHTML=S.state.jobs.slice().reverse().map(j=>`<button class="wb-reminder" data-job="${esc(j.id)}"><span class="fc-tag">${j.source==='demo'?'架空の失敗例':'手動登録'} / ${{waiting:'未対応',working:'対応中',done:'完了'}[j.status]}</span><strong>${esc(j.title)}</strong><small>${esc(j.eventId)} / ${esc(j.owner||'担当未設定')} / ${esc(j.due||'期限なし')}</small><p>${esc(j.note)}</p></button>`).join('')||'<p class="empty">引継ぎタスクはありません。実監視は未接続です。</p>';}
function jobState(){return JSON.stringify([...new FormData($('#wb-job-form')).entries()])}
function openJob(id=null){jobId=id;const j=S.state.jobs.find(j=>j.id===id),f=$('#wb-job-form');f.reset();for(const k of ['eventId','title','status','owner','due','note'])f.elements[k].value=j?.[k]??({status:'waiting'}[k]||'');f.elements.eventId.disabled=!!j;jobClean=jobState();$('#wb-job-error').textContent='';$('#wb-job-dialog').showModal();}
function closeJob(){if(jobClean!==jobState()&&!confirm('引継ぎの未保存入力を破棄しますか？'))return;$('#wb-job-dialog').close();}
$('#wb-job-add').onclick=()=>openJob();$('#wb-job-close').onclick=closeJob;$('#wb-job-dialog').addEventListener('cancel',e=>{e.preventDefault();closeJob()});$('#wb-jobs-list').onclick=e=>{const b=e.target.closest('[data-job]');if(b)openJob(b.dataset.job)};
$('#wb-job-form').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget,existing=S.state.jobs.find(j=>j.id===jobId),next=clone(S.state),j={id:existing?.id||crypto.randomUUID(),source:existing?.source||'manual'};for(const k of ['eventId','title','status','owner','due','note'])j[k]=f.elements[k].value.trim();if(existing)next.jobs=next.jobs.map(x=>x.id===j.id?j:x);else next.jobs.push(j);await logWork(next,`引継ぎを${existing?'更新':'登録'}：${j.eventId} / ${j.status} / ${j.owner} / ${j.note}`);$('#wb-job-dialog').close();notify('引継ぎを保存しました。');}catch(err){$('#wb-job-error').textContent=err.message;}};
$('#wb-job-demo').onclick=async ()=>{try{if(S.state.jobs.some(j=>j.eventId==='DEMO-FAIL-001')){notify('同じ受付IDの例は登録済みです。二重登録はしません。');return;}const next=clone(S.state);next.jobs.push({id:crypto.randomUUID(),eventId:'DEMO-FAIL-001',source:'demo',title:'架空の例：書類読取が完了しなかった',status:'waiting',owner:'',due:today(),note:'実際のAI処理ではありません。手動で内容確認し、担当者と対応結果を記録する練習用です。'});await logWork(next,'架空の失敗例を1件登録（実AI処理なし）');}catch(err){notify(err.message);}};
function renderAcquisition(){const f=$('#wb-source-form'),current=f.elements.customer.value;f.elements.customer.innerHTML=customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} / ${esc(c.acquisition?.channel||'不明')}</option>`).join('');if(customers.some(c=>c.id===current))f.elements.customer.value=current;syncSource();$('#wb-acquisition-table').innerHTML=W.acquisition(customers,S.state).map(r=>`<tr><th>${esc(r.channel)}</th><td>${r.customers}</td><td>${r.cases}</td><td>${r.contracts}</td><td>${r.purchases}</td><td>${yen(r.fee)}</td><td>${yen(r.budget)}</td><td>${r.customers?yen(Math.round(r.budget/r.customers)):'—'}</td></tr>`).join('');}
function syncSource(){const f=$('#wb-source-form'),c=customers.find(c=>c.id===f.elements.customer.value);f.elements.channel.value=c?.acquisition?.channel||'不明';f.elements.campaign.value=c?.acquisition?.campaign||'';}
for(const id of ['wb-source-form','wb-budget-form'])$('#'+id).elements.channel.innerHTML=W.channels.map(k=>`<option>${esc(k)}</option>`).join('');$('#wb-source-form').elements.customer.onchange=syncSource;
$('#wb-source-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,cid=f.elements.customer.value,channel=f.elements.channel.value,campaign=f.elements.campaign.value.trim();if(await persist(customers.map(c=>c.id===cid?{...c,acquisition:{channel,campaign},history:[...c.history,{at:stamp(),text:'集客経路：'+channel+' / '+campaign}]}:c))){render();notify('集客経路を保存しました。');}};
$('#wb-budget-form').onsubmit=async e=>{e.preventDefault();try{const f=e.currentTarget,next=clone(S.state),ch=f.elements.channel.value;next.budgets[ch]=F.amount(f.elements.amount.value);await logWork(next,'広告費累計：'+ch+' / '+yen(next.budgets[ch]));notify('広告費累計を更新しました。');}catch(err){notify(err.message);}};
$('#wb-lock').onchange=async e=>{try{await S.setLocked(e.target.checked);renderWorkbench();notify(S.locked?'書込ロックを有効にしました。':'書込ロックを解除しました。');}catch(err){e.target.checked=S.locked;notify(err.message);}};
$('#wb-export').onclick=()=>{try{const work=clone(S.state);W.validateWork(work);W.validateCustomers(customers,work);download('osanai-crm-backup-'+today()+'.json',JSON.stringify({format:'osanai-crm-backup',version:5,exportedAt:stamp(),customers,work},null,2));notify('バックアップファイルを作成しました。');}catch(err){$('#wb-backup-error').textContent=err.message;}};
$('#wb-import-file').onchange=async e=>{backupPreview=null;$('#wb-backup-preview').hidden=true;$('#wb-restore').hidden=true;try{const file=e.target.files?.[0];if(!file)return;if(file.size>12000000)throw Error('バックアップは12MB以内にしてください。');const b=W.parseBackup(await file.text());backupPreview=b;$('#wb-backup-preview').textContent=`復元内容：顧客 ${b.customers.length}件 / 案件 ${W.allCases(b.customers).length}件 / 銀行明細 ${b.work.bankRows.length}件 / 引継ぎ ${b.work.jobs.length}件。添付・通知・履歴も含め、現在のデータを置き換えます。`;$('#wb-backup-preview').hidden=false;$('#wb-restore').hidden=false;$('#wb-backup-error').textContent='';}catch(err){$('#wb-backup-error').textContent=err.message;}e.target.value='';};
$('#wb-restore').onclick=async ()=>{if(!backupPreview||!confirm('表示したバックアップで現在の全データを置き換えますか？ このブラウザの未保存の変更は失われます。'))return;try{await S.restore(backupPreview.customers,backupPreview.work);customers=backupPreview.customers;document.querySelectorAll('dialog[open]').forEach(d=>d.close());selectedId=null;render();backupPreview=null;$('#wb-backup-preview').hidden=true;$('#wb-restore').hidden=true;$('#wb-backup-error').textContent='';notify('バックアップを復元しました。');}catch(err){$('#wb-backup-error').textContent=err.message;}};
$('#reset').onclick=async ()=>{if(!confirm('このブラウザの顧客・売上・案件・入金・通知・添付・銀行明細・引継ぎ・業務設定をすべて消し、架空サンプルへ戻しますか？'))return;try{const fresh=seed();await S.restore(fresh,W.defaults());customers=fresh;reportAnchor=today();$('#report-date').value=reportAnchor;setView('all');notify('全デモデータを初期状態へ戻しました。');}catch(err){notify(err.message);}};
$('#wb-nav').onclick=()=>$('#wb-tools').scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-wb-open]').forEach(b=>b.onclick=()=>openTool(b.dataset.wbOpen));$('#wb-document-list').onclick=e=>{const b=e.target.closest('[data-wb-case]');if(b)openCaseEditor(b.dataset.wbCase)};
$('#wb-reminders-list').onclick=e=>{const c=e.target.closest('[data-reminder-case]'),u=e.target.closest('[data-reminder-customer]'),j=e.target.closest('[data-reminder-job]');if(c)openCaseEditor(c.dataset.reminderCase);else if(u)openCustomer(u.dataset.reminderCustomer);else if(j)openJob(j.dataset.reminderJob);};
window.addEventListener('crm-render',renderWorkbench);window.addEventListener('storage',e=>{if(['osanai-crm-workbench-v5','osanai-crm-write-lock-v5'].includes(e.key))notify('別のタブで業務データが変わりました。再読み込みして最新状態を確認してください。');});
setInterval(()=>{if(!document.hidden)renderReminders()},60000);renderWorkbench();
})();
